# DO NOT COMMIT THIS FILE TO GITHUB

NEWS_API_KEY = "your_news_api_key_here"
POLYGON_API_KEY = "your_polygon_api_key_here"
TRADIER_ACCESS_TOKEN = "your_tradier_access_token_here"
password = "MyStrongPassword123"
